name: Build LaTeX document
on: 
  - pull_request
  - workflow_dispatch
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install python and pygmentize
        run: sudo apt install python3 python3-pip && pip install Pygments 
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ./main.tex
          latexmk_shell_escape: true
      - name: Upload main.pdf
        uses: actions/upload-artifact@v2
        with:
          name: Slides
          path: ./main.pdf
